# Generated by Django 5.2.15 on 2026-07-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0016_idp_authn_requests_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='idp',
            name='want_assertions_signed',
            field=models.BooleanField(default=False, verbose_name='Want Assertions Signed'),
        ),
    ]
