# Generated by Django 5.2.15 on 2026-07-01 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0017_idp_want_assertions_signed'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdPAttributeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid', models.CharField(blank=True, db_index=True, max_length=200)),
                ('attributes', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_logs', to='sp.idp')),
            ],
            options={
                'verbose_name': 'assertion attribute log',
                'verbose_name_plural': 'assertion attribute logs',
                'ordering': ('-created_on',),
            },
        ),
    ]
