# Generated by Django 5.2.15 on 2026-07-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0018_idpattributelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='idp',
            name='email_auth_errors_to_admins',
            field=models.BooleanField(default=True, help_text='When enabled, failed SAML authentications are logged at error level (triggering Django ADMINS emails if configured).', verbose_name='Email auth errors to admins'),
        ),
    ]
