# Generated by Django 5.2.15 on 2026-07-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0019_idp_email_auth_errors_to_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='idp',
            name='auth_failed_message',
            field=models.TextField(blank=True, help_text='Shown to a user who authenticates with the IdP but has no MyCE account. Leave blank to use the default message.', verbose_name='Authentication failed message'),
        ),
    ]
