# Generated by Django 5.2.15 on 2026-07-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0020_idp_auth_failed_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='idp',
            name='log_response_attributes',
            field=models.BooleanField(default=True, help_text='When enabled, store one IdPAttributeLog row (all SAML attributes) for every response from this IdP. Disable for IdPs where retaining the attribute payload is undesirable.', verbose_name='Log response attributes'),
        ),
    ]
